
package com.ms.encuestas.models.segcen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISegCenServicios", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISegCenServicios {


    /**
     * 
     * @param strPHostName
     * @param strPIP
     * @param intPMayor
     * @param intPMinor
     * @param strPContrasenia
     * @param strPUsuario
     * @param strPCodigoAplicacion
     * @param intPVersion
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidarUsuarioApp", action = "http://tempuri.org/ISegCenServicios/ValidarUsuarioApp")
    @WebResult(name = "ValidarUsuarioAppResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidarUsuarioApp", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.ValidarUsuarioApp")
    @ResponseWrapper(localName = "ValidarUsuarioAppResponse", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.ValidarUsuarioAppResponse")
    public String validarUsuarioApp(
        @WebParam(name = "str_pUsuario", targetNamespace = "http://tempuri.org/")
        String strPUsuario,
        @WebParam(name = "str_pContrasenia", targetNamespace = "http://tempuri.org/")
        String strPContrasenia,
        @WebParam(name = "str_pCodigoAplicacion", targetNamespace = "http://tempuri.org/")
        String strPCodigoAplicacion,
        @WebParam(name = "int_pMayor", targetNamespace = "http://tempuri.org/")
        Integer intPMayor,
        @WebParam(name = "int_pMinor", targetNamespace = "http://tempuri.org/")
        Integer intPMinor,
        @WebParam(name = "int_pVersion", targetNamespace = "http://tempuri.org/")
        Integer intPVersion,
        @WebParam(name = "str_pIP", targetNamespace = "http://tempuri.org/")
        String strPIP,
        @WebParam(name = "str_pHostName", targetNamespace = "http://tempuri.org/")
        String strPHostName);

    /**
     * 
     * @param strPIdUsuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ObtenerNombreUsuario", action = "http://tempuri.org/ISegCenServicios/ObtenerNombreUsuario")
    @WebResult(name = "ObtenerNombreUsuarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtenerNombreUsuario", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.ObtenerNombreUsuario")
    @ResponseWrapper(localName = "ObtenerNombreUsuarioResponse", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.ObtenerNombreUsuarioResponse")
    public String obtenerNombreUsuario(
        @WebParam(name = "str_pIdUsuario", targetNamespace = "http://tempuri.org/")
        String strPIdUsuario);

    /**
     * 
     * @param strPHostName
     * @param strPIP
     * @param intPMayor
     * @param intPMinor
     * @param strPContrasenia
     * @param strPUsuario
     * @param strPCodigoAplicacion
     * @param intPSoloPermitidas
     * @param intPVersion
     * @return
     *     returns com.ms.encuestas.models.segcen.PermisosLBE
     */
    @WebMethod(operationName = "VerificaUsuarioObtienePermisos", action = "http://tempuri.org/ISegCenServicios/VerificaUsuarioObtienePermisos")
    @WebResult(name = "VerificaUsuarioObtienePermisosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VerificaUsuarioObtienePermisos", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.VerificaUsuarioObtienePermisos")
    @ResponseWrapper(localName = "VerificaUsuarioObtienePermisosResponse", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.VerificaUsuarioObtienePermisosResponse")
    public PermisosLBE verificaUsuarioObtienePermisos(
        @WebParam(name = "str_pUsuario", targetNamespace = "http://tempuri.org/")
        String strPUsuario,
        @WebParam(name = "str_pContrasenia", targetNamespace = "http://tempuri.org/")
        String strPContrasenia,
        @WebParam(name = "str_pCodigoAplicacion", targetNamespace = "http://tempuri.org/")
        String strPCodigoAplicacion,
        @WebParam(name = "int_pMayor", targetNamespace = "http://tempuri.org/")
        Integer intPMayor,
        @WebParam(name = "int_pMinor", targetNamespace = "http://tempuri.org/")
        Integer intPMinor,
        @WebParam(name = "int_pVersion", targetNamespace = "http://tempuri.org/")
        Integer intPVersion,
        @WebParam(name = "int_pSoloPermitidas", targetNamespace = "http://tempuri.org/")
        Integer intPSoloPermitidas,
        @WebParam(name = "str_pIP", targetNamespace = "http://tempuri.org/")
        String strPIP,
        @WebParam(name = "str_pHostName", targetNamespace = "http://tempuri.org/")
        String strPHostName);

    /**
     * 
     * @param intPMayor
     * @param intPMinor
     * @param strPContrasenia
     * @param strPUsuario
     * @param strPCodigoAplicacion
     * @param intPSoloPermitidas
     * @param intPVersion
     * @return
     *     returns com.ms.encuestas.models.segcen.PermisosLBE
     */
    @WebMethod(operationName = "VerificaUsuarioObtienePermisosWithoutIPHostName", action = "http://tempuri.org/ISegCenServicios/VerificaUsuarioObtienePermisosWithoutIPHostName")
    @WebResult(name = "VerificaUsuarioObtienePermisosWithoutIPHostNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VerificaUsuarioObtienePermisosWithoutIPHostName", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.VerificaUsuarioObtienePermisosWithoutIPHostName")
    @ResponseWrapper(localName = "VerificaUsuarioObtienePermisosWithoutIPHostNameResponse", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.VerificaUsuarioObtienePermisosWithoutIPHostNameResponse")
    public PermisosLBE verificaUsuarioObtienePermisosWithoutIPHostName(
        @WebParam(name = "str_pUsuario", targetNamespace = "http://tempuri.org/")
        String strPUsuario,
        @WebParam(name = "str_pContrasenia", targetNamespace = "http://tempuri.org/")
        String strPContrasenia,
        @WebParam(name = "str_pCodigoAplicacion", targetNamespace = "http://tempuri.org/")
        String strPCodigoAplicacion,
        @WebParam(name = "int_pMayor", targetNamespace = "http://tempuri.org/")
        Integer intPMayor,
        @WebParam(name = "int_pMinor", targetNamespace = "http://tempuri.org/")
        Integer intPMinor,
        @WebParam(name = "int_pVersion", targetNamespace = "http://tempuri.org/")
        Integer intPVersion,
        @WebParam(name = "int_pSoloPermitidas", targetNamespace = "http://tempuri.org/")
        Integer intPSoloPermitidas);

    /**
     * 
     * @param intPMayor
     * @param intPMinor
     * @param strPContrasenia
     * @param strPUsuario
     * @param strPCodigoAplicacion
     * @param intPVersion
     * @return
     *     returns com.ms.encuestas.models.segcen.PermisosLBE
     */
    @WebMethod(operationName = "VerificaUsuarioObtienePermisosWithoutSoloPermitidasIPHostName", action = "http://tempuri.org/ISegCenServicios/VerificaUsuarioObtienePermisosWithoutSoloPermitidasIPHostName")
    @WebResult(name = "VerificaUsuarioObtienePermisosWithoutSoloPermitidasIPHostNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VerificaUsuarioObtienePermisosWithoutSoloPermitidasIPHostName", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.VerificaUsuarioObtienePermisosWithoutSoloPermitidasIPHostName")
    @ResponseWrapper(localName = "VerificaUsuarioObtienePermisosWithoutSoloPermitidasIPHostNameResponse", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.VerificaUsuarioObtienePermisosWithoutSoloPermitidasIPHostNameResponse")
    public PermisosLBE verificaUsuarioObtienePermisosWithoutSoloPermitidasIPHostName(
        @WebParam(name = "str_pUsuario", targetNamespace = "http://tempuri.org/")
        String strPUsuario,
        @WebParam(name = "str_pContrasenia", targetNamespace = "http://tempuri.org/")
        String strPContrasenia,
        @WebParam(name = "str_pCodigoAplicacion", targetNamespace = "http://tempuri.org/")
        String strPCodigoAplicacion,
        @WebParam(name = "int_pMayor", targetNamespace = "http://tempuri.org/")
        Integer intPMayor,
        @WebParam(name = "int_pMinor", targetNamespace = "http://tempuri.org/")
        Integer intPMinor,
        @WebParam(name = "int_pVersion", targetNamespace = "http://tempuri.org/")
        Integer intPVersion);

    /**
     * 
     * @param intPMayor
     * @param intPMinor
     * @param strPCodigoAplicacion
     * @param strIdUsuario
     * @param intPVersion
     * @return
     *     returns com.ms.encuestas.models.segcen.ArrayOfRolBE
     */
    @WebMethod(operationName = "ObtenerRolesUsuarioAplicacion", action = "http://tempuri.org/ISegCenServicios/ObtenerRolesUsuarioAplicacion")
    @WebResult(name = "ObtenerRolesUsuarioAplicacionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtenerRolesUsuarioAplicacion", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.ObtenerRolesUsuarioAplicacion")
    @ResponseWrapper(localName = "ObtenerRolesUsuarioAplicacionResponse", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.ObtenerRolesUsuarioAplicacionResponse")
    public ArrayOfRolBE obtenerRolesUsuarioAplicacion(
        @WebParam(name = "str_pCodigoAplicacion", targetNamespace = "http://tempuri.org/")
        String strPCodigoAplicacion,
        @WebParam(name = "int_pMayor", targetNamespace = "http://tempuri.org/")
        Integer intPMayor,
        @WebParam(name = "int_pMinor", targetNamespace = "http://tempuri.org/")
        Integer intPMinor,
        @WebParam(name = "int_pVersion", targetNamespace = "http://tempuri.org/")
        Integer intPVersion,
        @WebParam(name = "strIdUsuario", targetNamespace = "http://tempuri.org/")
        String strIdUsuario);

    /**
     * 
     * @param strpIdUsuario
     * @return
     *     returns com.ms.encuestas.models.segcen.UsuarioBE
     */
    @WebMethod(operationName = "ObtenerUsuario", action = "http://tempuri.org/ISegCenServicios/ObtenerUsuario")
    @WebResult(name = "ObtenerUsuarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtenerUsuario", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.ObtenerUsuario")
    @ResponseWrapper(localName = "ObtenerUsuarioResponse", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.ObtenerUsuarioResponse")
    public UsuarioBE obtenerUsuario(
        @WebParam(name = "strpIdUsuario", targetNamespace = "http://tempuri.org/")
        String strpIdUsuario);

    /**
     * 
     * @param intPMayor
     * @param intPMinor
     * @param strPCodigoAplicacion
     * @param strPIdUsuario
     * @param intPSoloPermitidas
     * @param intPVersion
     * @return
     *     returns com.ms.encuestas.models.segcen.AccesosBE
     */
    @WebMethod(operationName = "ObtenerAccesosApp", action = "http://tempuri.org/ISegCenServicios/ObtenerAccesosApp")
    @WebResult(name = "ObtenerAccesosAppResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtenerAccesosApp", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.ObtenerAccesosApp")
    @ResponseWrapper(localName = "ObtenerAccesosAppResponse", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.ObtenerAccesosAppResponse")
    public AccesosBE obtenerAccesosApp(
        @WebParam(name = "str_pIdUsuario", targetNamespace = "http://tempuri.org/")
        String strPIdUsuario,
        @WebParam(name = "str_pCodigoAplicacion", targetNamespace = "http://tempuri.org/")
        String strPCodigoAplicacion,
        @WebParam(name = "int_pMayor", targetNamespace = "http://tempuri.org/")
        Integer intPMayor,
        @WebParam(name = "int_pMinor", targetNamespace = "http://tempuri.org/")
        Integer intPMinor,
        @WebParam(name = "int_pVersion", targetNamespace = "http://tempuri.org/")
        Integer intPVersion,
        @WebParam(name = "int_pSoloPermitidas", targetNamespace = "http://tempuri.org/")
        Integer intPSoloPermitidas);

    /**
     * 
     * @param strPIdUsuario
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "VerificarExistenciaUsuario", action = "http://tempuri.org/ISegCenServicios/VerificarExistenciaUsuario")
    @WebResult(name = "VerificarExistenciaUsuarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VerificarExistenciaUsuario", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.VerificarExistenciaUsuario")
    @ResponseWrapper(localName = "VerificarExistenciaUsuarioResponse", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.VerificarExistenciaUsuarioResponse")
    public Boolean verificarExistenciaUsuario(
        @WebParam(name = "str_pIdUsuario", targetNamespace = "http://tempuri.org/")
        String strPIdUsuario);

    /**
     * 
     * @param strPValorAnterior
     * @param strPHostName
     * @param strPCampo
     * @param strPIP
     * @param intPMayor
     * @param intPMinor
     * @param strPNombreEntidad
     * @param strPCodigoAplicacion
     * @param strPIdUsuario
     * @param strPValorNuevo
     * @param intPVersion
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AgregarLogCambios", action = "http://tempuri.org/ISegCenServicios/AgregarLogCambios")
    @WebResult(name = "AgregarLogCambiosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AgregarLogCambios", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.AgregarLogCambios")
    @ResponseWrapper(localName = "AgregarLogCambiosResponse", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.AgregarLogCambiosResponse")
    public Boolean agregarLogCambios(
        @WebParam(name = "str_pCodigoAplicacion", targetNamespace = "http://tempuri.org/")
        String strPCodigoAplicacion,
        @WebParam(name = "int_pMayor", targetNamespace = "http://tempuri.org/")
        Integer intPMayor,
        @WebParam(name = "int_pMinor", targetNamespace = "http://tempuri.org/")
        Integer intPMinor,
        @WebParam(name = "int_pVersion", targetNamespace = "http://tempuri.org/")
        Integer intPVersion,
        @WebParam(name = "str_pIdUsuario", targetNamespace = "http://tempuri.org/")
        String strPIdUsuario,
        @WebParam(name = "str_pNombreEntidad", targetNamespace = "http://tempuri.org/")
        String strPNombreEntidad,
        @WebParam(name = "str_pCampo", targetNamespace = "http://tempuri.org/")
        String strPCampo,
        @WebParam(name = "str_pValorAnterior", targetNamespace = "http://tempuri.org/")
        String strPValorAnterior,
        @WebParam(name = "str_pValorNuevo", targetNamespace = "http://tempuri.org/")
        String strPValorNuevo,
        @WebParam(name = "str_pHostName", targetNamespace = "http://tempuri.org/")
        String strPHostName,
        @WebParam(name = "str_pIP", targetNamespace = "http://tempuri.org/")
        String strPIP);

    /**
     * 
     * @param intPIdRegistroLogon
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RegistrarLogLogout", action = "http://tempuri.org/ISegCenServicios/RegistrarLogLogout")
    @WebResult(name = "RegistrarLogLogoutResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RegistrarLogLogout", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.RegistrarLogLogout")
    @ResponseWrapper(localName = "RegistrarLogLogoutResponse", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.RegistrarLogLogoutResponse")
    public Boolean registrarLogLogout(
        @WebParam(name = "int_pIdRegistroLogon", targetNamespace = "http://tempuri.org/")
        Integer intPIdRegistroLogon);

    /**
     * 
     * @param strPHostName
     * @param strPIP
     * @param intPMayor
     * @param intPMinor
     * @param strPCodigoAplicacion
     * @param strPIdUsuario
     * @param intPVersion
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "AgregarLogLogon", action = "http://tempuri.org/ISegCenServicios/AgregarLogLogon")
    @WebResult(name = "AgregarLogLogonResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AgregarLogLogon", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.AgregarLogLogon")
    @ResponseWrapper(localName = "AgregarLogLogonResponse", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.AgregarLogLogonResponse")
    public Integer agregarLogLogon(
        @WebParam(name = "str_pCodigoAplicacion", targetNamespace = "http://tempuri.org/")
        String strPCodigoAplicacion,
        @WebParam(name = "int_pMayor", targetNamespace = "http://tempuri.org/")
        Integer intPMayor,
        @WebParam(name = "int_pMinor", targetNamespace = "http://tempuri.org/")
        Integer intPMinor,
        @WebParam(name = "int_pVersion", targetNamespace = "http://tempuri.org/")
        Integer intPVersion,
        @WebParam(name = "str_pIdUsuario", targetNamespace = "http://tempuri.org/")
        String strPIdUsuario,
        @WebParam(name = "str_pHostName", targetNamespace = "http://tempuri.org/")
        String strPHostName,
        @WebParam(name = "str_pIP", targetNamespace = "http://tempuri.org/")
        String strPIP);

    /**
     * 
     * @param codigoAplicacion
     * @param idUsuario
     * @return
     *     returns com.ms.encuestas.models.segcen.ResultadoValidacionBE
     */
    @WebMethod(operationName = "ValidarEstadoCuenta", action = "http://tempuri.org/ISegCenServicios/ValidarEstadoCuenta")
    @WebResult(name = "ValidarEstadoCuentaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidarEstadoCuenta", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.ValidarEstadoCuenta")
    @ResponseWrapper(localName = "ValidarEstadoCuentaResponse", targetNamespace = "http://tempuri.org/", className = "com.ms.encuestas.models.segcen.ValidarEstadoCuentaResponse")
    public ResultadoValidacionBE validarEstadoCuenta(
        @WebParam(name = "idUsuario", targetNamespace = "http://tempuri.org/")
        String idUsuario,
        @WebParam(name = "codigoAplicacion", targetNamespace = "http://tempuri.org/")
        String codigoAplicacion);

}
