
package com.ms.encuestas.services.segcen;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SegCenServicio", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://pvida73.pacificovida.com/swSegCen/service.svc?wsdl")
public class SegCenServicio
    extends Service
{

    private final static URL SEGCENSERVICIO_WSDL_LOCATION;
    private final static WebServiceException SEGCENSERVICIO_EXCEPTION;
    private final static QName SEGCENSERVICIO_QNAME = new QName("http://tempuri.org/", "SegCenServicio");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://pvida73.pacificovida.com/swSegCen/service.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEGCENSERVICIO_WSDL_LOCATION = url;
        SEGCENSERVICIO_EXCEPTION = e;
    }

    public SegCenServicio() {
        super(__getWsdlLocation(), SEGCENSERVICIO_QNAME);
    }

    public SegCenServicio(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEGCENSERVICIO_QNAME, features);
    }

    public SegCenServicio(URL wsdlLocation) {
        super(wsdlLocation, SEGCENSERVICIO_QNAME);
    }

    public SegCenServicio(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEGCENSERVICIO_QNAME, features);
    }

    public SegCenServicio(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SegCenServicio(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISegCenServicios
     */
    @WebEndpoint(name = "BasicHttpBinding_ISegCenServicios")
    public ISegCenServicios getBasicHttpBindingISegCenServicios() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISegCenServicios"), ISegCenServicios.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISegCenServicios
     */
    @WebEndpoint(name = "BasicHttpBinding_ISegCenServicios")
    public ISegCenServicios getBasicHttpBindingISegCenServicios(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISegCenServicios"), ISegCenServicios.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEGCENSERVICIO_EXCEPTION!= null) {
            throw SEGCENSERVICIO_EXCEPTION;
        }
        return SEGCENSERVICIO_WSDL_LOCATION;
    }

}
